### ISSUE TITLE
Missing Citation?

### ISSUE THREAD

**Issue by digantamisra98** [Andrew-Qibin/VisionPermutator#2]
The paper looks to be heavily inspired by our WACV paper - [Rotate to Attend: Convolutional Triplet Attention Module](https://openaccess.thecvf.com/content/WACV2021/papers/Misra_Rotate_to_Attend_Convolutional_Triplet_Attention_Module_WACV_2021_paper.pdf). Considering there is a mutual author in both the papers, we find it surprising that our paper wasn't at least mentioned in the literature review of this paper. We believe it is important and crucial in the academic space to ensure appropriate and relevant papers are cited.

**Comment by Andrew-Qibin** [comment]
Hi Diganta, sorry for missing that. I will add citation on our paper.

**Comment by digantamisra98** [comment]
Thank you for your consideration

**Comment by digantamisra98** [comment]
It's unfortunate that it has been over 3 months and this hasn't been resolved. I hope you take this into notice.
